### PR TITLE
for run away optimization

### PR DESCRIPTION
**Pull request by kadorek**

### CODE REVIEW

**Comment by kadorek** [comment]
"kac" and "edist" are garbage variable  :). i copied and pasted from my old code. sorry.

**Comment by ButtmanNumbaVan** [comment]
Ok, I tested and it works. Thank you and please make ur changes mergeable so I can merge it

**Comment by kadorek** [comment]
i am not good at using github features. how can i understand that the changes are mergeable. @ButtmanNumbaVan

**Comment by ButtmanNumbaVan** [comment]
Ok I will fix it myself but I found a problem when there are more than one enemy and if their  move directions arent identical it starts to flee to one port then switch to another and agai and again

**Comment by kadorek** [comment]
Thanks for your fix. Did you see the bug that u mentioned. I remember as the hero moves when enemy closer than to it to gate. If stands at gate the distance is zero so enemy coudnt be closer than hero to gate.

**Pull request closed without merging**
